### ISSUE TITLE
Ruby-Graphviz is GPL so you are in violation of the license

### ISSUE THREAD

**Issue by ioquatix** [zeisler/visualize_ruby#1]
You should use the graphviz gem instead.

**Comment by zeisler** [comment]
@ioquatix thank you. You suggestion has been completed.

**Comment by ioquatix** [comment]
Awesome, hopefully it wasn't too much of a shock. The reason why I made that gem was due to licensing issues.

**Comment by zeisler** [comment]
@ioquatix thanks for doing the work. My interactions with the gem was all done in one place so it was not too much work.

**Comment by ioquatix** [comment]
That sounds like a good design.
