### ISSUE TITLE
Ruby version requirement

### ISSUE THREAD

**Issue by daveseward** [zeisler/visualize_ruby#10]
Hey, was just trying to play around with this gem and hit a problem with line 127 in builder.rb:

```
def wrap_bare_methods(ruby_code)
      wrapped_ruby_code = <<~RUBY
        class BareMethodsClass
          #{ruby_code.source}
        end
      RUBY
```

Did some digging and it seems that ```<<~``` is a ruby 2.3 thing.  I'm running 2.2.10 so it caused a crash for me.  Your gem spec lists ```>= 2.1```, so maybe could update this or perhaps change it back to a ```<<-``` for old ruby?

**Comment by zeisler** [comment]
Sorry for the delay could you @daveseward open a PR for this?

**Comment by zeisler** [comment]
Version 0.16.0 contains is now constrained to equal or greater than ruby version 2.3

**Comment by daveseward** [comment]
Just saw this - thanks :)
