### ISSUE TITLE
Consider generating a sequence diagram

### ISSUE THREAD

**Issue by jwsloan** [zeisler/visualize_ruby#3]
I love this project!

There were a few of us that started https://github.com/nash-rb/sequence-diagram-rb with the same idea in mind. Our plan is/was to generate uml that can be converted to a sequence diagram. Are you familiar with http://plantuml.com/?

**Comment by zeisler** [comment]
Thanks for your support!

Sequence diagrams are an interesting idea. Most of what I've done is limited, for now, to the flow between methods within a class, but could be expanded. Too bad planuml is a java app, but it does use graphviz. I'm open to the idea, but not sure how it would all work. I'm open to you coming up with a plan of how this could work and a pull-request to follow.
