### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by driv3r** [zeisler/visualize_ruby#5]
Hi, great project! I was just wondering if it's possible or if it's planned to run it against a whole project, i.e. rails based, or something similar? 

On a side note, did you considered using [RubVM::AST](https://ruby-doc.com/core-trunk/RubyVM/AST.html)? 

Best,
Leszek

**Comment by zeisler** [comment]
Currently, it's scoped for single Ruby classes. A next step might be to able to parse interaction between different classes, but a whole Rails project is just too big for me to think about.

RubyVM::AST had just come out when I started working on this and I was much more familiar with the parser gem. It would be a lot of additional work with no know added value to switch over.
